[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
ghost_stops = "y8gjZcwDHqZ8Sz2Uziw5nxr2cWKGyAKaqtNAUJ2mKxh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".keypair.json"

[scripts]
test = "echo 'integration tests live in scripts/test-program.ts'"
